server:
  port: 9100

spring:
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: wangdong
    password: s3^@dKKD_354
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 30
    minIdle: 10
    maxWaite: 600000
logging:
  level:
    root: INFO
    com.chile.web.api: DEBUG

