server:
  port: 9000
spring:
  application:
    name: coupon
logging:
  level:
    root: INFO
    com.coupon.api.mapper: DEBUG
spring.datasource.url: jdbc:mysql://192.168.1.8:3306/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.username: wangdong
spring.datasource.password: s3^@dKKD_354
spring.datasource.validationQuery: SELECT 1 FROM DUAL
spring.datasource.logSlowSql: true
######################### Druid连接池的配置信息  #################
spring.datasource.initialSize: 5                                 #初始化连接大小
spring.datasource.minIdle: 5                                     #最小连接池数量
spring.datasource.maxActive: 20                                  #最大连接池数量
spring.datasource.maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
spring.druid.timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.druid.minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
spring.druid.validationQuery: SELECT 1 FROM DUAL            #测试连接
spring.druid.testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
spring.druid.testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
spring.druid.testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
spring.druid.poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
spring.druid.maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
spring.druid.filters: stat,wall,log4j                       #配置扩展插件，常用的插件有: >stat:监控统计  log4j:日志  wall:防御sql注入
spring.druid.connectionProperties: 'druid.stat.mergeSql: true;druid.stat.slowSqlMillis: 5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:message/mybatis-config.xml
  type-aliases-package: com.coupon.api.entity